#! /bin/sh

rm -r coffee-cj
mkdir coffee-cj

fella -o coffee-cj/class_tools.coffee  coffee/class_tools.coffee
fella -o coffee-cj/SuperEmitter.coffee coffee/SuperEmitter.coffee

coffee -o lib/ -cb coffee
coffee -o lib-cj/ -cb coffee-cj
