#! /bin/sh

rm -r coffee-cj
mkdir coffee-cj

node_modules/.bin/coffee node_modules/cjfella/main.coffee -o coffee-cj/class_tools.coffee  coffee/class_tools.coffee
node_modules/.bin/coffee node_modules/cjfella/main.coffee -o coffee-cj/SuperEmitter.coffee coffee/SuperEmitter.coffee

node_modules/.bin/coffee -o lib/ -cb coffee
node_modules/.bin/coffee -o lib-cj/ -cb coffee-cj
